import {useState} from 'react';
import {toCSV} from '../export';
import {renderOfflineMapPage,schoolsWithCoordinates,splitMapPages} from '../pdfMap';
const paths={pin:'M12 22s7-8 7-14a7 7 0 1 0-14 0c0 6 7 14 7 14z M12 5a3 3 0 1 0 0 6 3 3 0 0 0 0-6',line:'M3 21 21 3',polygon:'m12 2 10 7-4 13H6L2 9z',info:'M12 10v10 M12 4v2',erase:'m3 15 10-12 9 8-10 12H8z M8 10l9 8'};
export function MapTools({tools,onToolClick}) {return <div className="map-tools-container">{tools.map(t=><button key={t.id} className={'map-tool-btn '+(t.active?'active':'')} aria-label={t.title} aria-pressed={t.active} title={t.title} onClick={()=>onToolClick(t.id)}><svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d={paths[t.icon]}/></svg></button>)}</div>}
export function ResultsInfo({count,visible}){if(!visible)return null;return <div className="results-info" role="status">{count.toLocaleString('es-PE')} servicio(s) encontrado(s)</div>}
export function LoadingOverlay({visible}){if(!visible)return null;return <div className="loading-overlay" role="status"><div className="spinner"/>Cargando servicios educativos…</div>}
export function CoordDisplay({visible,lat,lng}){if(!visible)return null;return <div className="coord-display">y,x: {lat.toFixed(6)}, {lng.toFixed(6)}</div>}
export function ExportButton({data,onTable}){
 const [busy,setBusy]=useState(false),[error,setError]=useState('');
 function csv(){const url=URL.createObjectURL(new Blob(['\uFEFF'+toCSV(data)],{type:'text/csv;charset=utf-8;'}));const link=document.createElement('a');link.href=url;link.download='servicios_educativos.csv';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
 async function pdf(){setBusy(true);setError('');try{const [{jsPDF},{default:autoTable}]=await Promise.all([import('jspdf'),import('jspdf-autotable')]);const points=schoolsWithCoordinates(data);const mapIndexes=new Map(points.map((school,index)=>[school,index+1]));const pages=splitMapPages(points);const doc=new jsPDF({orientation:'landscape',unit:'mm',format:'a4',compress:true});if(pages.length){pages.forEach((page,index)=>{if(index)doc.addPage();doc.addImage(renderOfflineMapPage(points,page,index+1,pages.length),'PNG',8,8,281,169)});doc.addPage()}doc.setFontSize(16);doc.text('Mapa de Escuelas · Listado de servicios educativos',14,16);doc.setFontSize(9);doc.text(`Padrón local | ${data.length} resultados | ${points.length} con coordenadas | ${new Date().toLocaleDateString('es-PE')}`,14,23);if(!points.length)doc.text('No hay coordenadas válidas para dibujar el plano de ubicación.',14,31);autoTable(doc,{startY:30,head:[['N° mapa','Código modular','Nombre','Nivel','Centro poblado','Distrito','Provincia','Departamento','Latitud','Longitud']],body:data.map(s=>[mapIndexes.get(s)||'-',s.codigoModular,s.nombre,s.nivel,s.centroPoblado,s.distrito,s.provincia,s.departamento,s.lat,s.lng]),styles:{fontSize:7},headStyles:{fillColor:[22,63,99]}});doc.save('mapa_servicios_educativos.pdf')}catch{setError('No se pudo generar el PDF. Intente exportar CSV.')}finally{setBusy(false)}}
 return <div className="export-container">{error&&<p role="alert" className="error-message">{error}</p>}<div className="flex gap-2"><button className="export-btn" onClick={onTable}>Ver resultados</button><button className="export-btn" disabled={!data.length} onClick={csv}>Exportar CSV</button><button className="export-btn" disabled={busy||!data.length} onClick={pdf}>{busy?'Generando…':'Exportar PDF'}</button></div></div>
}
